# Application Configuration
spring.application.name=webapp-backend
server.port=8080

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

# Logging Configuration
logging.level.root=INFO

# Database Configuration
db.jdbcUrl=jdbc:mysql://localhost:3306/mydb
db.username=dbuser
db.password=dbpassword

# HikariCP Configuration
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000

# Spring DevTools Configuration
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# Actuator and Prometheus Configuration
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=*